version = 1

test_patterns = ["*/tests*"]

exclude_patterns = [
    ".pytest_cache/**",
    ".coverage",
    ".coveragerc",
    ".gitignore",
    "Pipfile",
    "Pipfile.lock"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"